blogs/forms/main.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField, StringField, BooleanField
from wtforms.validators import Optional, Length, DataRequired, ValidationError
from flask_ckeditor import CKEditorField


class PostForm(FlaskForm):
    title = StringField('标题', validators=[DataRequired(), Length(1, 60)])
    body = CKEditorField('', validators=[DataRequired(message='内容不能为空！'), Length(1, 100000)])
    notice = BooleanField('有人回复时，给我发送一封Email')
    save = SubmitField('保存草稿')
    publish = SubmitField('发布')
    save1 = SubmitField('附件')

blogs/blueprints/ajax.py
from flask import Blueprint, jsonify, render_template
from flask_login import current_user

from blogs.models.blogs import User, Notification

ajax_bp = Blueprint('ajax', __name__)


@ajax_bp.route('/get_profile/<int:user_id>')
def get_profile(user_id):
    if not current_user.is_authenticated:
        return jsonify(message='请先登录'), 403
    user = User.query.get_or_404(user_id)
    return render_template('main/profile_popup.html', user=user)


@ajax_bp.route('/notifications-count')
def notifications_count():
    if not current_user.is_authenticated:
        return jsonify(message='请先登录'), 403

    count = Notification.query.with_parent(current_user).filter_by(is_read=False).count()
    return jsonify(count=count)

blogs/blueprints/auth.py
from flask import Blueprint, redirect, url_for, flash, render_template
from flask_login import current_user, login_required, login_user, logout_user, login_fresh, confirm_login

from blogs.settings import Operations
from blogs.forms.auth import LoginForm, ForgetPasswordForm, ResetPasswordForm, RegisterForm
from blogs.models.blogs import User
from blogs.extensions import db
from blogs.utils import generate_token, validate_token, redirect_back
from blogs.emails import send_reset_password_email, send_confirm_email

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is not None and user.validate_password(form.password.data):
            if login_user(user, form.remember_me.data):
                flash('登录成功.', 'info')
                return redirect_back()
            else:
                flash('你的账号已被封禁。', 'warning')
                return redirect(url_for('main.index'))
        flash('无效的邮箱或者密码.', 'warning')
    return render_template('auth/login.html', form=form)


@auth_bp.route('/forget-password', methods=['GET', 'POST'])
def forget_password():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = ForgetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user:
            token = generate_token(user=user, operation=Operations.RESET_PASSWORD)
            send_reset_password_email(user=user, token=token)
            flash('重设密码邮件已发送，请查看你的邮箱。', 'info')
            return redirect(url_for('.login'))
        flash('无效的邮箱.', 'warning')
        form.email.data = ""
        return redirect(url_for('.forget_password'))
    return render_template('auth/reset_password.html', form=form)


@auth_bp.route('/reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is None:
            return redirect(url_for('main.index'))
        if validate_token(user=user, token=token, operation=Operations.RESET_PASSWORD,
                          new_password=form.password.data):
            flash('密码已更新', 'success')
            form.email.data = ""
            return redirect(url_for('.login'))
        else:
            flash('链接无效或者超时。', 'danger')
            return redirect(url_for('.forget_password'))
    return render_template('auth/reset_password.html', form=form)


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('成功登出', 'info')
    return redirect(url_for('main.index'))


@auth_bp.route('/register', methods=['POST', 'GET'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = RegisterForm()
    if form.validate_on_submit():
        username = form.username.data
        name = form.name.data
        email = form.email.data.lower()  # 小写处理
        password = form.password.data
        company = form.company.data
        user = User(username=username, email=email, company=company, name=name)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        send_confirm_email(user=user)
        flash('确认邮件已发送给系统管理员，请等待管理员确认', 'info')
        return redirect(url_for('.login'))
    return render_template('auth/register.html', form=form)


@auth_bp.route('/re-authenticate', methods=['GET', 'POST'])
@login_required
def re_authenticate():
    if login_fresh():
        return redirect(url_for('main.index'))

    form = LoginForm()
    if form.validate_on_submit() and current_user.validate_password(form.password.data):
        confirm_login()
        return redirect_back()
    return render_template('auth/login.html', form=form)

blogs/blueprints/main.py
from flask import render_template, Blueprint, send_from_directory, current_app, request, redirect, url_for, abort, flash
from flask_login import current_user, login_required
import os
import time
from flask_ckeditor import upload_success, upload_fail
import uuid

from blogs.models.blogs import File, Post, Group, User, Notification, Topic, Read
from blogs.extensions import db
from blogs.forms.main import PostForm
from blogs.utils import redirect_back, resize_image, rename_image
from blogs.noticifations import push_post_notification, push_collect_notification, push_notice_notification, \
    push_max_reported_post_notification, push_max_reported_topic_notification
from blogs.decorators import permission_required, confirm_required
from blogs.emails import send_new_post_email
from blogs.forms.admin import MigrateForm

main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index():
    all_groups = Group.query.filter_by(status_id=4).all()
    apart_groups = Group.query.filter_by(status_id=3).all()
    limit_groups = Group.query.filter_by(status_id=2).all()
    member_groups = Group.query.filter_by(status_id=1).all()
    return render_template('main/index.html', all_groups=all_groups, limit_groups=limit_groups,
                           groups=apart_groups, member_groups=member_groups)


@main_bp.route('/new_topic/<int:group_id>', methods=['POST', 'GET'])
@login_required
@confirm_required
def new_topic(group_id):
    if group_id == 3:
        abort(403)
    group = Group.query.get_or_404(group_id)
    if group.status_id == 1 and not current_user.can('MEMBER'):
        abort(403)

    if group.status_id == 2 and not current_user.can('MEMBER'):
        abort(403)

    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data
        topic = Topic(name=title, body=body, group_id=group_id, author=current_user._get_current_object())
        db.session.add(topic)
        if form.publish.data:
            current_user.read(topic)  # 标记自己发表的文章为已读
            db.session.commit()
            if form.notice.data:
                current_user.notice(topic)
            flash('主题已发表', 'success')
            return redirect(url_for('main.show_topic', topic_id=topic.id))
        elif form.save.data:
            topic.saved = True
            db.session.commit()
            flash('主题已保存', 'success')
            return redirect(url_for('user.draft_topic'))
        elif form.save1.data:
            topic.saved = True
            db.session.commit()
            flash('请上传附件', 'info')
            return redirect(url_for('.upload_topic', topic_id=topic.id))
    return render_template('main/new_topic.html', form=form, group=group)


@main_bp.route('/show_topic/<int:topic_id>')
def show_topic(topic_id):
    topic = Topic.query.get_or_404(topic_id)
    topic.read_time += 1
    db.session.commit()
    if topic.saved and current_user != topic.author and not current_user.can('MODERATE'):
        abort(404)
    if not current_user.is_authenticated and topic.group.status_id != 4:
        flash('请登录', 'info')
        return redirect(url_for('auth.login'))

    if current_user.is_authenticated and not current_user.confirmed and topic.group.status_id != 4:
        flash('请等待管理员确认您的账户', 'warning')
        return redirect(url_for('main.index'))

    if not current_user.can('MEMBER') and topic.group.status_id == 1:
        abort(403)

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['POST_PER_PAGE']
    pagination = Post.query.with_parent(topic).filter_by(saved=False).\
        order_by(Post.timestamp.asc()).paginate(page, per_page)
    posts = pagination.items
    if current_user.is_authenticated:
        current_user.read(topic)
    form = MigrateForm()
    return render_template('main/show_topic.html', topic=topic, posts=posts, pagination=pagination, form=form)


@main_bp.route('/new_post/<int:topic_id>', methods=['POST', 'GET'])
@login_required
@confirm_required
def new_post(topic_id):
    topic = Topic.query.get_or_404(topic_id)
    if topic.group.status_id == 1 and not current_user.can('MEMBER'):
        abort(403)
    if topic.group.status_id == 2 and not current_user.can('MEMBER'):
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data
        post = Post(title=title, body=body, topic=topic, author=current_user._get_current_object())
        db.session.add(post)
        if form.publish.data:
            db.session.commit()
            if topic.receivers:
                for notice in topic.receivers:
                    send_new_post_email(receiver=notice.receiver, topic=topic, user=current_user)
            if form.notice.data:
                current_user.notice(topic)
            if current_user != topic.author and topic.author.receive_post_notification:
                push_post_notification(post=post, receiver=topic.author)
            flash('帖子已发表', 'success')
            return redirect(url_for('main.show_post', post_id=post.id))
        elif form.save.data:
            post.saved = True
            db.session.commit()
            flash('帖子已保存', 'success')
            return redirect(url_for('user.draft_post'))
        elif form.save1.data:
            post.saved = True
            db.session.commit()
            flash('请上传附件', 'info')
            return redirect(url_for('.upload_post', post_id=post.id))
    form.title.data = 'Re:'+topic.name
    return render_template('main/new_post.html', form=form, topic=topic)


@main_bp.route('/uploads/<path:filename>')
def get_file(filename):
    return send_from_directory(current_app.config['UPLOAD_PATH'], filename)


@main_bp.route('/upload', methods=['POST'])
def upload():
    f = request.files.get('upload')  # 获取上传图片文件对象
    extension = f.filename.split('.')[1].lower()
    if extension not in ['jpg', 'gif', 'png', 'jpeg']:  # 验证文件类型示例
        return upload_fail(message='只能上传图片！')  # 返回upload_fail调用
    filename = uuid.uuid4().hex + '.' + extension
    if os.path.exists(os.path.join(current_app.config['UPLOAD_PATH'], filename)):
        filename = rename_image(filename)
    f.save(os.path.join(current_app.config['UPLOAD_PATH'], filename))
    resize_image(request.files['upload'], filename, current_app.config['PHOTO_SIZE']['medium'])
    url = url_for('.get_file', filename=filename)
    return upload_success(url, filename) # 返回upload_success调用


@main_bp.route('/post/<int:post_id>', methods=['POST', 'GET'])
def show_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.saved and current_user != post.author and not current_user.can('MODERATE'):
        abort(404)
    if not current_user.is_authenticated and post.topic.group.status_id != 4:
        flash('请登录', 'info')
        return redirect(url_for('auth.login'))

    if current_user.is_authenticated and not current_user.confirmed and post.topic.group.status_id != 4:
        flash('请等待管理员确认您的账户', 'warning')
        return redirect(url_for('main.index'))
    if not current_user.can('MEMBER') and post.topic.group.status_id == 1:
        abort(403)
    return render_template('main/post.html', post=post)


@main_bp.route('/avatars/<path:filename>')
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@main_bp.route('/post/<int:post_id>/d', methods=['POST'])
@login_required
@confirm_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user != post.author and current_user != post.topic.group.admin and not current_user.can('MODERATE'):
        abort(403)

    db.session.delete(post)
    db.session.commit()
    flash('成功删除帖子', 'success')
    return redirect_back()


@main_bp.route('/topic/<int:topic_id>/delete', methods=['POST'])
@login_required
@confirm_required
def delete_topic(topic_id):
    topic = Topic.query.get_or_404(topic_id)
    if current_user != topic.group.admin and not current_user.can('MODERATE') and current_user != topic.author:
        abort(403)
    db.session.delete(topic)
    db.session.commit()
    flash('删除主题成功', 'success')
    return redirect_back()


@main_bp.route('/notifications')
@login_required
def show_notifications():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['NOTIFICATION_PER_PAGE']
    notifications = Notification.query.with_parent(current_user)
    filter_rule = request.args.get('filter')
    if filter_rule == 'unread':
        notifications = notifications.filter_by(is_read=False)

    pagination = notifications.order_by(Notification.timestamp.desc()).paginate(page, per_page)
    notifications = pagination.items
    return render_template('main/notifications.html', pagination=pagination, notifications=notifications)


@main_bp.route('/notification/read/<int:notification_id>', methods=['POST'])
@login_required
def read_notification(notification_id):
    notification = Notification.query.get_or_404(notification_id)
    if current_user != notification.receiver:
        abort(403)

    notification.is_read = True
    db.session.commit()
    flash('通知已读。', 'success')
    return redirect(url_for('.show_notifications'))


@main_bp.route('/notifications/read/all', methods=['POST'])
@login_required
def read_all_notification():
    for notification in current_user.notifications:
        notification.is_read = True
    db.session.commit()
    flash('所有通知已读', 'success')
    return redirect(url_for('.show_notifications'))


@main_bp.route('/reply/post/<int:replied_id>', methods=['POST', 'GET'])
@login_required
@confirm_required
def reply_post(replied_id):
    replied = Post.query.get_or_404(replied_id)
    if replied.topic.group.status_id == 1 and not current_user.can('MEMBER'):
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data
        author = current_user._get_current_object()
        post = Post(body=body,

blogs/templates/main/_post.html
<div class="card-body border_grey">
    <div class="row card-body-header">
        <div class="col-sm-4">
            <a href="{{ url_for('user.index', username=post.author.username) }}">
                <img src="{{ url_for('main.get_avatar', filename=post.author.avatar_s) }}"
                     class="avatar-m profile-popover float-left img-fluid"
                    data-href="{{ url_for('ajax.get_profile', user_id=post.author.id) }}">
            </a>
            <a href="{{ url_for('user.index', username=post.author.username) }}" class="profile-popover"
                data-href="{{ url_for('ajax.get_profile', user_id=post.author.id) }}">
                {{ post.author.username}}</a><br>
            <small class="text-muted">
            主题<a href="{{ url_for('user.index', username=post.author.username) }}">
                <span class="badge badge-info">
                    {{ post.author.publish_topic_count() }}
                </span></a></small>
        </div>
        <div class="col-sm-4">
            {% if post.topic.group.status_id !=2 or current_user.can('MEMBER')%}
            <div class="dropdown nav-item float-left">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                   aria-expanded="false">
                    <span class="oi oi-ellipses"></span>
                </a>
                <div class="dropdown-menu" role="menu">
                    <a href="{{ url_for('main.reply_post', replied_id=post.id)}}" class="dropdown-item">
                        <span class="oi oi-share"></span>回复</a>
                    {% if current_user == post.author or current_user == post.topic.group.admin
                        or current_user.can('MODERATE') %}
                        <a href="{{ url_for('main.edit_post', post_id=post.id) }}" class="dropdown-item text-muted">
                            <span class="oi oi-pencil">编辑</span>
                        </a>
                    {% endif %}
                    {% if current_user.can('MEMBER') %}
                        <form method="post" action="{{ url_for('main.report_post', post_id=post.id) }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <button type="submit" class="dropdown-item text-warning">
                                <span class="oi oi-warning"></span>举报
                            </button>
                        </form>
                    {% endif %}
                    {% if current_user==post.topic.group.admin or current_user.can('MODERATE') or
                        current_user==post.author %}
                        <a data-toggle="modal" data-target="#confirm-delete" href="#!"
                           data-href="{{ url_for('main.delete_post', post_id=post.id,
                           next=url_for('main.show_topic', topic_id=post.topic_id)) }}"
                            class="dropdown-item text-danger"><span class="oi oi-x"></span> 删除</a>
                    {% endif %}
                </div>
            </div>
            {% endif %}
        </div>
        <div class="col-sm-4">
            <span class="oi oi-clock text-muted small float-right">
                {{ moment(post.timestamp).format('llll') }}</span>
        </div>
    </div>
    {% if post.replied %}
        <blockquote class="small text-muted border_grey">
            <span class="float-right">{{ moment(post.replied.timestamp).format('llll') }}</span>
                由{{ post.replied.author.username }}<br>
                {{ post.replied.body|striptags|truncate(150,ture,'......') }}
        </blockquote>
    {% endif %}
    <h5>{{ post.title }}</h5>
    <div class="overflow">{{ post.body|safe }}</div>
    {% if post.files %}
        <div class="border border-light">
            <h4>附件：</h4>
            {% for file in post.files %}
                {{ file_display(file)}}
            {% endfor %}
        </div>
    {% endif %}
</div>

blogs/templates/main/_topic.html
<div class="card-body border_grey">
    <div class="row card-body-header">
        <div class="col-sm-4">
            <a href="{{ url_for('user.index', username=topic.author.username) }}">
                <img src="{{ url_for('main.get_avatar', filename=topic.author.avatar_s) }}"
                     class="avatar-m profile-popover float-left img-fluid"
                    data-href="{{ url_for('ajax.get_profile', user_id=topic.author.id) }}">
            </a>
            <a href="{{ url_for('user.index', username=topic.author.username) }}" class="profile-popover"
                data-href="{{ url_for('ajax.get_profile', user_id=topic.author.id) }}">
                {{ topic.author.username}}</a><br>
            <small class="text-muted">
            主题<a href="{{ url_for('user.index', username=topic.author.username) }}">
                <span class="badge badge-info">
                    {{ topic.author.publish_topic_count() }}
                </span></a></small>
        </div>
        <div class="col-sm-4">
            {% if topic.group.status_id !=2 or current_user.can('MEMBER')%}
            <div class="dropdown nav-item float-left">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                   aria-expanded="false">
                    <span class="oi oi-ellipses"></span>
                </a>
                <div class="dropdown-menu" role="menu">
                    <a href="{{ url_for('main.new_post', topic_id=topic.id)}}" class="dropdown-item">
                        <span class="oi oi-share"></span>回复</a>
                    {% if current_user == topic.author or current_user == topic.group.admin
                        or current_user.can('MODERATE') %}
                        <a href="{{ url_for('main.edit_topic', topic_id=topic.id) }}" class="dropdown-item text-muted">
                            <span class="oi oi-pencil">编辑</span>
                        </a>
                    {% endif %}
                    {% if current_user.can('MEMBER') %}
                        <form method="post" action="{{ url_for('main.report_topic', topic_id=topic.id) }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <button type="submit" class="dropdown-item text-warning">
                                <span class="oi oi-warning"></span>举报
                            </button>
                        </form>
                    {% endif %}
                    {% if current_user==topic.group.admin or current_user.can('MODERATE') or
                        current_user==topic.author %}
                        <a data-toggle="modal" data-target="#confirm-delete" href="#!"
                           data-href="{{ url_for('main.delete_topic', topic_id=topic.id,
                           next=url_for('main.show_group', group_id=topic.group_id)) }}"
                            class="dropdown-item text-danger"><span class="oi oi-x"></span> 删除</a>
                    {% endif %}
                </div>
            </div>
            {% endif %}
        </div>
        <div class="col-sm-4">
            <span class="oi oi-clock text-muted small float-right">
                {{ moment(topic.timestamp).format('llll') }}</span>
        </div>
    </div>
    <div class="overflow">{{ topic.body|safe }}</div>
    {% if topic.files %}
        <div class="border border-light">
            <h4>附件：</h4>
            {% for file in topic.files %}
                {{ file_display(file)}}
            {% endfor %}
        </div>
    {% endif %}
</div>

blogs/templates/main/basic.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-9">
            {% block base_content %}{% endblock %}
        </div>
        <div class="col-md-3">
            <div class="card">
                <div class="card-header bg-light">
                    <h6>用户资料</h6>
                </div>
                {% if current_user.is_authenticated %}
                    <div class="card-body">
                        <a href="{{ url_for('user.index', username=current_user.username) }}">
                            <img src="{{ url_for('main.get_avatar', filename=current_user.avatar_m) }}"
                                 class="img-fluid float-left avatar-l">
                        </a>
                        <strong>{{ current_user.username }}</strong><br>
                        <a href="{{ url_for('user.index', username=current_user.username) }}" class="text-dark">
                            <span class="oi oi-home"></span>用户主页</a><br>
                        <a href="{{ url_for('auth.logout') }}" class="text-dark"><span class="oi oi-power-standby">退出</span></a><br>
                        <br class="clear_float">
                        <hr>
                        <span class="oi oi-file"></span>
                        <a href="{{ url_for('user.index', username=current_user.username)}}" class="text-dark">查看我的帖子</a><br>
                        <span class="oi oi-bell"></span>
                        <span class="{% if notification_count == 0 %}hidden{% endif %} badge badge-danger
                              badge-notification" id="notification-badge"
                              data-href="{{ url_for('ajax.notifications_count') }}">{{ notification_count }}</span>
                        <a href="{{ url_for('main.show_notifications', filter='unread') }}" class="text-dark">通知
                        </a>
                    </div>
                {% else %}
                    <div class="card-body">
                        <a href="{{ url_for('auth.login') }}"><span class="oi oi-power-standby"></span> 登录</a>
                        <br>
                        <br>
                        <a href="{{ url_for('auth.register') }}"><span class="oi oi-pencil"></span> 注册</a>
                    </div>
                {% endif %}
            </div>
            <br>
            <br>
            <div class="card">
                <div class="card-header bg-light">
                    <h6>{{ group3.name }}</h6>
                </div>
                <div class="card-body">
                    <small class="text-muted">{{ group3.intro }}</small>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blogs/templates/main/group.html
{% extends 'main/basic.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}{{ group.name }}{% endblock %}

{% block header %}
    <div class="page-header">
        <p><span class="oi oi-home text-muted"></span>
            <a href="{{ url_for('main.index')}}" class="text-dark text-muted">论坛首页</a>&nbsp;&nbsp;
            <small class="oi oi-chevron-left text-muted"></small>&nbsp;
            <a href="{{ url_for('main.show_group', group_id=group.id) }}" class="text-dark text-muted">
                {{ group.name }}</a>
        </p>
    </div>
{% endblock %}

{% block base_content %}
    <h1>{{ group.name }}</h1>
    <div class="page-header">
        <span class="float-right">
            主题:<span class="badge badge-info">{{ group.get_topic_count() }}</span>
        </span>
        {% if group.status_id !=2 or current_user.can('MEMBER') %}
            <a href="{{ url_for('main.new_topic', group_id=group.id) }}"
               class="btn btn-primary {% if group.id == 3%}disabled{% endif %}" role="button">
                发帖<span class="oi oi-pencil"></span> </a>
        {% endif %}
    </div>
    {% if group.get_topic_count() %}
        <table class="table">
            <thead>
            <tr class="card-header bg-primary text-white">
                <th>主题</th>
                <th><span class="oi oi-chat"></span> </th>
                <th><span class="oi oi-eye"></span> </th>
                <th><span class="oi oi-clock"></span></th>
            </tr>
            </thead>
            {% for topic in group.top_topic() %}
                <tr>
                    <td><small class="badge badge-danger">置顶</small>
                        {% if current_user.is_authenticated and not current_user.is_reading(topic) %}
                            <small class="oi oi-media-record text-danger"></small>
                        {% endif %}
                        <a href="{{ url_for('main.show_topic', topic_id=topic.id) }}">
                        {{ topic.name }}</a><br>
                        <small>由
                            <a href="{{ url_for('user.index', username=topic.author.username) }}">
                                {{ topic.author.username }}</a></small>
                    </td>
                    <td>{{ topic.get_post_count() }}</td>
                    <td>{{ topic.read_time }}</td>
                    <td class="text-muted">
                        {% if not topic.posts %}
                            由<a class="profile-popover" href="{{ url_for('user.index', username=topic.author.username) }}"
                                data-href="{{ url_for('ajax.get_profile', user_id=topic.author_id) }}">
                            {{ topic.author.username }}</a>发布<br>
                            {{ moment(topic.timestamp).format('llll')}}
                        {% else %}
                            由<a class="profile-popover"
                               data-href="{{ url_for('ajax.get_profile', user_id=topic.get_last_post().author_id) }}"
                                    href="{{ url_for('user.index', username=topic.get_last_post().author.username) }}">
                                {{ topic.get_last_post().author.username }}</a>发布<br>
                            {{ moment(topic.get_last_post().timestamp).format('llll')}}</td>
                        {% endif %}
                </tr>
            {% endfor %}
            {% for topic in topics %}
                <tr>
                    <td>{% if current_user.is_authenticated and not current_user.is_reading(topic) %}
                            <small class="oi oi-media-record text-danger"></small>
                        {% endif %}
                        <a href="{{ url_for('main.show_topic', topic_id=topic.id) }}">
                        {{ topic.name }}</a><br>
                        <small>由
                            <a href="{{ url_for('user.index', username=topic.author.username) }}">
                                {{ topic.author.username }}</a></small>
                    </td>
                    <td>{{ topic.get_post_count() }}</td>
                    <td>{{ topic.read_time }}</td>
                    <td class="text-muted">
                        {% if not topic.get_last_post() %}
                            由<a class="profile-popover" href="{{ url_for('user.index', username=topic.author.username) }}"
                                data-href="{{ url_for('ajax.get_profile', user_id=topic.author_id) }}">
                            {{ topic.author.username }}</a>发布<br>
                            {{ moment(topic.timestamp).format('llll')}}
                        {% else %}
                            由<a class="profile-popover"
                               data-href="{{ url_for('ajax.get_profile', user_id=topic.get_last_post().author_id) }}"
                                    href="{{ url_for('user.index', username=topic.get_last_post().author.username) }}">
                                {{ topic.get_last_post().author.username }}</a>发布<br>
                            {{ moment(topic.get_last_post().timestamp).format('llll')}}</td>
                        {% endif %}
                </tr>
            {% endfor %}
        </table>
        {{ render_pagination(pagination, align='center') }}
    {% endif %}
{% endblock %}