blogs/forms/user.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField, HiddenField, PasswordField, BooleanField
from wtforms.validators import Length, DataRequired, Regexp, EqualTo, ValidationError, Optional, Email
from flask_wtf.file import FileField, FileAllowed, FileRequired
from flask_login import current_user

from blogs.models.blogs import User


class EditProfileForm(FlaskForm):
    username = StringField('用户名*', validators=[DataRequired(), Length(1, 30),
                                               Regexp('^[a-zA-Z0-9]*$', message='用户名只能由a-z,A-Z和0-9组成。')])
    name = StringField('真实姓名', validators=[Length(0, 20), Optional()])
    phone = StringField('手机号码', validators=[Optional(), Length(1, 11),
                                            Regexp("^1(?:3\d|4[4-9]|5[0-35-9]|6[67]|7[013-8]|8\d|9\d)\d{8}$")])
    position = StringField('职位', validators=[Optional(), Length(0, 30)])
    submit = SubmitField('更新')

    def validate_username(self, field):
        if field.data != current_user.username and User.query.filter_by(username=field.data).first():
            raise ValidationError('用户名已存在。')



class UploadAvatarForm(FlaskForm):
    upload = FileField('上传图片', validators=[FileRequired(), FileAllowed(['jpg', 'png'],
                                                                       '仅允许 .jpg 或者 .png后缀的图片。')])
    submit = SubmitField('上传')


class CropAvatarForm(FlaskForm):
    x = HiddenField()
    y = HiddenField()
    w = HiddenField()
    h = HiddenField()
    submit = SubmitField('剪切并保存')


class ChangePasswordForm(FlaskForm):
    old_password = PasswordField('旧密码', validators=[DataRequired(), Length(8, 128)])
    password = PasswordField('新密码', validators=[DataRequired(), Length(8, 128), EqualTo('password2')])
    password2 = PasswordField('请再输一次新密码', validators=[DataRequired(), Length(8, 128)])
    submit = SubmitField('保存')


class NotificationSettingForm(FlaskForm):
    receive_post_notification = BooleanField('新回帖通知')
    receive_collect_notification = BooleanField('新收藏者通知')
    receive_notice_notification = BooleanField('新订阅者通知')
    submit = SubmitField('保存')


class ChangeEmailForm(FlaskForm):
    email = StringField('新邮箱', validators=[DataRequired(), Length(1, 254), Email()])
    submit = SubmitField('提交')

    def validate_email(self, field):
        if field.data != self.user.email and User.query.filter_by(email=field.data).first():
            raise ValidationError('此邮箱已注册过本论坛。')

blogs/blueprints/ajax.py
from flask import Blueprint, jsonify, render_template
from flask_login import current_user

from blogs.models.blogs import User, Notification

ajax_bp = Blueprint('ajax', __name__)


@ajax_bp.route('/get_profile/<int:user_id>')
def get_profile(user_id):
    if not current_user.is_authenticated:
        return jsonify(message='请先登录'), 403
    user = User.query.get_or_404(user_id)
    return render_template('main/profile_popup.html', user=user)


@ajax_bp.route('/notifications-count')
def notifications_count():
    if not current_user.is_authenticated:
        return jsonify(message='请先登录'), 403

    count = Notification.query.with_parent(current_user).filter_by(is_read=False).count()
    return jsonify(count=count)

blogs/blueprints/user.py
from flask import Blueprint, request, current_app, render_template, flash, redirect, url_for, abort
from flask_login import current_user, logout_user, login_required, fresh_login_required
import os

from blogs.models.blogs import User, Post, Collect, Notice, Topic, Notification
from blogs.forms.user import EditProfileForm, CropAvatarForm, UploadAvatarForm, ChangePasswordForm, \
    NotificationSettingForm, ChangeEmailForm
from blogs.extensions import db, avatars
from blogs.utils import flash_errors, generate_token, validate_token, redirect_back
from blogs.decorators import confirm_required
from blogs.settings import Operations
from blogs.emails import send_user_confirm_email

user_bp = Blueprint('user', __name__)


@user_bp.route('/<username>')
@login_required
@confirm_required
def index(username):
    user = User.query.filter_by(username=username).first()
    if user == current_user and not user.active:
        logout_user()

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['TOPIC_PER_PAGE']
    pagination = Topic.query.with_parent(user).filter_by(saved=False).order_by(Topic.timestamp.desc()).\
        paginate(page, per_page)
    topics = pagination.items
    return render_template('user/topics.html', user=user, pagination=pagination, topics=topics)


@user_bp.route('/settings/profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.name = form.name.data
        current_user.phone = form.phone.data
        current_user.position = form.position.data
        db.session.commit()
        flash('信息已更新', 'success')
        return redirect(url_for('.index', username=current_user.username))
    form.username.data = current_user.username
    form.name.data = current_user.name
    form.phone.data = current_user.phone
    form.position.data = current_user.position
    return render_template('user/setting/edit_profile.html', form=form)


@user_bp.route('/settings/avatar')
@login_required
@confirm_required
def change_avatar():
    upload_form = UploadAvatarForm()
    crop_form = CropAvatarForm()
    return render_template('user/setting/change_avatar.html', upload_form=upload_form, crop_form=crop_form)


@user_bp.route('/settings/avatar/upload', methods=['POST'])
@login_required
@confirm_required
def upload_avatar():
    form = UploadAvatarForm()
    if form.validate_on_submit():
        image = form.upload.data
        filename = avatars.save_avatar(image)
        current_user.avatar_raw = filename
        db.session.commit()
        flash('图片已上传，请剪切图片。', 'success')
    flash_errors(form)
    return redirect(url_for('.change_avatar'))


@user_bp.route('/settings/avatar/crop', methods=['POST'])
@login_required
@confirm_required
def crop_avatar():
    form = CropAvatarForm()
    if form.validate_on_submit() and current_user.avatar_raw:
        x = form.x.data
        y = form.y.data
        w = form.w.data
        h = form.h.data
        filenames = avatars.crop_avatar(current_user.avatar_raw, x, y, w, h)
        current_user.avatar_s = filenames[0]
        current_user.avatar_m = filenames[1]
        current_user.avatar_l = filenames[2]
        db.session.commit()
        flash('头像已更新', 'success')
    flash_errors(form)
    return redirect(url_for('.change_avatar'))


@user_bp.route('/settings/change-password', methods=['GET', 'POST'])
@fresh_login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit() and current_user.validate_password(form.old_password.data):
        current_user.set_password(form.password.data)
        db.session.commit()
        flash('密码已更新', 'success')
        return redirect(url_for('.index', username=current_user.username))
    form.old_password.data = ''
    return render_template('user/setting/change_password.html', form=form)


@user_bp.route('/settings/notification', methods=['GET', 'POST'])
@login_required
def notification_setting():
    form = NotificationSettingForm()
    if form.validate_on_submit():
        current_user.receive_collect_notification = form.receive_collect_notification.data
        current_user.receive_post_notification = form.receive_post_notification.data
        current_user.receive_notice_notification = form.receive_notice_notification.data
        db.session.commit()
        flash('通知设置已更新', 'success')
        return redirect(url_for('user.index', username=current_user.username))
    form.receive_collect_notification.data = current_user.receive_collect_notification
    form.receive_post_notification.data = current_user.receive_post_notification
    form.receive_notice_notification.data = current_user.receive_notice_notification
    return render_template('user/setting/edit_notification.html', form=form)


@user_bp.route('/my_collections')
@login_required
@confirm_required
def collection():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['POST_PER_PAGE']
    pagination = Collect.query\
        .with_parent(current_user)\
        .order_by(Collect.timestamp.desc()).paginate(page, per_page)
    collects = pagination.items
    return render_template('user/collections.html', collects=collects, pagination=pagination, user=current_user)


@user_bp.route('/draft_posts')
@login_required
@confirm_required
def draft_post():
    drafts = Post.query.with_parent(current_user).filter_by(saved=True).order_by(Post.timestamp.desc()).all()
    return render_template('user/post_drafts.html', drafts=drafts, user=current_user)


@user_bp.route('/draft_topics')
@login_required
@confirm_required
def draft_topic():
    drafts = Topic.query.with_parent(current_user).filter_by(saved=True).order_by(Topic.timestamp.desc()).all()
    return render_template('user/topic_drafts.html', drafts=drafts, user=current_user)


@user_bp.route('/topics_noticed')
@login_required
@confirm_required
def topics_noticed():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['TOPIC_PER_PAGE']
    pagination = Notice.query \
        .with_parent(current_user) \
        .order_by(Notice.timestamp.desc()).paginate(page, per_page)
    notices = pagination.items
    return render_template('user/topics_noticed.html', notices=notices, user=current_user, pagination=pagination)


@user_bp.route('/posts/<username>')
@login_required
@confirm_required
def my_posts(username):
    user = User.query.filter_by(username=username).first()
    if user == current_user and not user.active :
        logout_user()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['TOPIC_PER_PAGE']
    pagination = Post.query.with_parent(user).filter_by(saved=False)\
        .order_by(Post.timestamp.desc()).paginate(page, per_page)
    posts = pagination.items
    return render_template('user/posts.html', posts=posts, pagination=pagination, user=user)


@user_bp.route('/settings/change-email', methods=['GET', 'POST'])
@fresh_login_required
def change_email_request():
    form = ChangeEmailForm()
    if form.validate_on_submit():
        token = generate_token(user=current_user, operation=Operations.CHANGE_EMAIL, new_email=form.email.data.lower())
        send_user_confirm_email(to=form.email.data, user=current_user, token=token)
        flash('确认邮件已发送，请检查你的邮箱。', 'info')
        return redirect(url_for('.index', username=current_user.username))
    return render_template('user/setting/change_email.html', form=form)


@user_bp.route('/change-email/<token>')
@login_required
def change_email(token):
    if validate_token(user=current_user, token=token, operation=Operations.CHANGE_EMAIL):
        flash('邮箱已更新。', 'success')
        return redirect(url_for('.index', username=current_user.username))
    else:
        flash('无效或者过时的令牌', 'warning')
        return redirect(url_for('.change_email_request'))


@user_bp.route('/delete_notification/<int:notification_id>', methods=['POST'])
@login_required
def delete_notification(notification_id):
    notification = Notification.query.get_or_404(notification_id)
    if notification.receiver != current_user:
        abort(403)

    db.session.delete(notification)
    db.session.commit()
    flash('已成功删除通知。', 'success')
    return redirect_back()


@user_bp.route('/delete_all_notification', methods=['POST'])
@login_required
def delete_all_notification():
    notifications = Notification.query.with_parent(current_user).all()
    for notification in notifications:
        db.session.delete(notification)
    db.session.commit()
    flash('已成功删除所有通知信息。', 'success')
    return redirect_back()

blogs/templates/user/basic.html
{% extends 'base.html' %}

{% block header %}
    <h1 class="page-header">{{ user.username }}的个人主页</h1>{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-3">
            <a href="{% if current_user == user %}{{ url_for('.change_avatar') }}{% else %}#{% endif %}"
               title="更换头像">
                <img class="img-fluid rounded avatar-xl"
                     src="{{ url_for('main.get_avatar', filename=user.avatar_l) }}">
            </a>
            <h3>{{ user.username }}
                <small class="text-muted">
                    {% if user.name %}
                        {% if current_user.can('MEMBER') or user==current_user %}
                            ({{ user.name }})
                        {% endif %}
                    {% endif %}
                    {% if user.is_admin %}
                        <span class="text-danger small">管理员</span>
                    {% endif %}
                    {% if current_user.is_admin %}
                        <a href="{{ url_for('admin.edit_profile_admin', username=user.username) }}"
                           class="btn btn-outline-primary btn-sm">编辑</a>
                    {% endif %}
                </small>
            </h3>
            <p>
                主题：{{ user.publish_topic_count() }}<br>
                邮箱：<a href="mailto:{{ user.email }}">{{ user.email }}</a><br>
                {% if current_user.can('MEMBER') or current_user==user %}
                    {% if user.phone %}手机：{{ user.phone }}<br>{% endif %}
                    {% if user.company %}公司：{{ user.company }}{% endif %}
                {% endif %}
            </p>
            {% if current_user == user %}
                <p><a class="btn btn-primary btn-sm" href="{{ url_for('user.edit_profile')}}">
                    <span class="oi oi-pencil"></span> 个人设置</a>&nbsp;
                    <a href="{{url_for('user.change_avatar') }}" class="btn btn-primary btn-sm">
                    <span class="oi oi-pencil"></span> 更换头像</a></p>
            {% endif %}
        </div>
        <div class="col-sm-9">
            <ul class="nav nav-tabs" role="tablist">
                {{ render_nav_item('user.index', '发表的主题', user.publish_topic_count(), username=user.username) }}
                {{ render_nav_item('user.my_posts', '回复的帖子', user.publish_post_count(), username=user.username) }}
                {% if user == current_user %}
                    {{ render_nav_item('user.collection', '我的收藏', current_user.collections|length) }}
                    {{ render_nav_item('user.topics_noticed', '订阅的主题', current_user.notices|length) }}
                    {{ render_nav_item('user.draft_post', '草稿--帖子', current_user.saved_post_count() )}}
                    {{ render_nav_item('user.draft_topic', '草稿--主题', current_user.saved_topic_count() )}}
                {% endif %}
            </ul>
            {% block user_content %}{% endblock %}
        </div>
    </div>
{% endblock %}

blogs/templates/user/collections.html
{% extends 'user/basic.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}我的收藏{% endblock %}

{% block user_content %}
    {% if collects %}
        <table class="table">
            <thead>
            <tr class="card-header bg-primary text-white">
                <th>主题</th>
                <th>组</th>
                <th><span class="oi oi-chat"></span> </th>
                <th><span class="oi oi-clock"></span></th>
                <th><span class="oi oi-wrench"></span> </th>
            </tr>
            </thead>
            {% for collect in collects %}
                <tr>
                    <td><a href="{{ url_for('main.show_topic', topic_id=collect.collected_id) }}">
                        {{ collect.collected.name }}</a></td>
                    <td><a href="{{ url_for('main.show_group', group_id=collect.collected.group_id) }}">
                        {{ collect.collected.group.name }}</a> </td>
                    <td>{{ collect.collected.get_post_count() }}</td>
                    <td class="text-muted">
                        {{ moment(collect.collected.timestamp).format('llll')}}<br>
                        由<a href="{{ url_for('user.index', username=collect.collected.author.username)}}">
                            {{ collect.collected.author.username }}
                        </a> 发布
                    </td>
                    <td>
                        <form method="post" action="{{ url_for('main.uncollect', topic_id=collect.collected_id) }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <button type="submit" class="btn btn-outline-secondary btn-sm">
                                <span class="oi oi-x"></span> 取消收藏
                            </button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <div class="page-footer">
            {{ render_pagination(pagination, align='center') }}
        </div>
    {% else %}
        <div class="tip text-center">
            <p class="text-muted">暂无内容</p>
        </div>
    {% endif %}
{% endblock %}

blogs/templates/user/post_drafts.html
{% extends 'user/basic.html' %}

{% block title %}草稿管理{% endblock %}

{% block user_content %}
    {% if drafts %}
        <table class="table">
            <thead>
            <tr class="card-header bg-primary text-white">
                <th>主题</th>
                <th>保存于</th>
                <th>操作</th>
            </tr>
            </thead>
            {% for draft in drafts %}
                <tr>
                    <td><a href="{{ url_for('main.show_topic', topic_id=draft.topic_id) }}">
                        {{ draft.topic.name }}</a></td>
                    <td class="text-muted">
                        <a href="{{ url_for('main.edit_post', post_id=draft.id) }}">{{ draft.title }}</a><br>
                        {{ moment(draft.timestamp).format('llll')}}</td>
                    <td><a href="{{ url_for('main.edit_post', post_id=draft.id) }}"
                                class="btn btn-outline-primary">编辑草稿</a>&nbsp;&nbsp;
                        <button data-toggle="modal" data-target="#confirm-delete" href="#!"
                           data-href="{{ url_for('main.delete_post', post_id=draft.id, next=request.full_path) }}"
                            class="btn btn-outline-danger inline">删除</button>
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <div class="tip text-center">
            <p class="text-muted">暂无内容</p>
        </div>
    {% endif %}
{% endblock %}

blogs/templates/user/posts.html
{% extends 'user/basic.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}{{ user.username }}发表的帖子{% endblock %}

{% block user_content %}
    {% if posts %}
        <table class="table">
            <thead>
            <tr class="card-header bg-primary text-white">
                <th>主题</th>
                <th>组</th>
                <th><span class="oi oi-clock"></span></th>
                {% if user == current_user or current_user.can('MODERATE') %}
                    <th><span class="oi oi-wrench"></span></th>{% endif %}
            </tr>
            </thead>
            {% for post in posts %}
                <tr>
                    <td><a href="{{ url_for('main.show_topic', topic_id=post.topic_id) }}">{{ post.topic.name }}</a><br>
                        由<a href="{{ url_for('user.index', username=post.topic.author.username) }}">
                            {{ post.topic.author.username}}</a>
                        </td>
                    <td><a href="{{ url_for('main.show_group', group_id=post.topic.group_id) }}">
                        {{ post.topic.group.name }}</a></td>
                    <td class="text-muted">
                        <a href="{{ url_for('main.show_post', post_id=post.id) }}" class="small text-dark">
                            {{ post.title }}</a><br>
                        {{ moment(post.timestamp).format('llll')}}</td>
                    {% if user==current_user or current_user.can('MODERATE') %}<td>
                        <a data-toggle="modal" data-target="#confirm-delete" href="#!"
                           data-href="{{ url_for('main.delete_post', post_id=post.id, next=request.full_path) }}"
                            class="btn btn-sm btn-outline-danger"><span class="oi oi-x"></span> 删除</a>&nbsp;&nbsp;
                        <a href="{{ url_for('main.edit_post', post_id=post.id) }}" class="btn btn-sm btn-outline-primary">
                            <span class="oi oi-pencil">编辑</span>
                        </a>
                    </td>{% endif %}
                </tr>
            {% endfor %}
        </table>
        <div class="page-footer">
            {{ render_pagination(pagination, align='center') }}
        </div>
    {% else %}
        <div class="tip text-center">
            <p class="text-muted">暂无内容</p>
        </div>
    {% endif %}
{% endblock %}

blogs/templates/user/topic_drafts.html
{% extends 'user/basic.html' %}

{% block title %}草稿管理{% endblock %}

{% block user_content %}
    {% if drafts %}
        <table class="table">
            <thead>
            <tr class="card-header bg-primary text-white">
                <th>组名</th>
                <th>主题名</th>
                <th>保存于</th>
                <th>操作</th>
            </tr>
            </thead>
            {% for draft in drafts %}
                <tr>
                    <td><a href="{{ url_for('main.show_group', group_id=draft.group_id) }}">
                        {{ draft.group.name }}</a></td>
                    <td><a href="{{ url_for('main.edit_topic', topic_id=draft.id) }}">{{ draft.name }}</a></td>
                    <td class="text-muted">{{ moment(draft.timestamp).format('llll')}}</td>
                    <td><a href="{{ url_for('main.edit_topic', topic_id=draft.id) }}"
                                class="btn btn-outline-primary">编辑草稿</a>
                        <button data-toggle="modal" data-target="#confirm-delete" href="#!"
                           data-href="{{ url_for('main.delete_topic', topic_id=draft.id, next=request.full_path) }}"
                            class="btn btn-outline-danger inline">删除</button>
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <div class="tip text-center">
            <p class="text-muted">暂无内容</p>
        </div>
    {% endif %}
{% endblock %}

blogs/templates/user/topics.html
{% extends 'user/basic.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}{{ user.username }}的主页{% endblock %}

{% block user_content %}
    {% if topics %}
        <table class="table">
            <thead>
            <tr class="card-header bg-primary text-white">
                <th>主题</th>
                <th>组</th>
                <th><span class="oi oi-chat"></span> </th>
                <th><span class="oi oi-eye"></span> </th>
                <th><span class="oi oi-envelope-closed"></span> </th>
                <th><span class="oi oi-clock"></span></th>
                {% if user==current_user or current_user.can('MODERATE') %}
                    <th><span class="oi oi-wrench"></span> </th>{% endif %}
            </tr>
            </thead>
            {% for topic in topics %}
                <tr>
                    <td><a href="{{ url_for('main.show_topic', topic_id=topic.id) }}">{{ topic.name }}</a><br>
                        <small class="text-muted"> {{ moment(topic.timestamp).format('llll') }}</small>
                    </td>
                    <td><a href="{{ url_for('main.show_group', group_id=topic.group_id) }}">
                        {{ topic.group.name }}</a></td>
                    <td>{{ topic.get_post_count() }}</td>
                    <td>{{ topic.read_time }}</td>
                    <td>{{ topic.receivers|length }}</td>
                    <td class="text-muted">
                        {% if topic.get_last_post() %}
                            由<a class="profile-popover"
                               data-href="{{ url_for('ajax.get_profile', user_id=topic.get_last_post().author_id) }}"
                                    href="{{ url_for('user.index', username=topic.get_last_post().author.username) }}">
                                {{ topic.get_last_post().author.username }}</a>发布<br>
                            {{ topic.get_last_post().title }}<br>
                            {{ moment(topic.get_last_post().timestamp).format('llll')}}
                        {% else %}
                            {{ moment(topic.timestamp).format('llll')}}
                        {% endif %}
                    </td>
                    {% if user==current_user or current_user.can('MODERATE') %}<td>
                        <a data-toggle="modal" data-target="#confirm-delete" href="#!"
                           data-href="{{ url_for('main.delete_topic', topic_id=topic.id, next=request.full_path) }}"
                            class="btn btn-sm btn-outline-danger"><span class="oi oi-x"></span> 删除</a>
                        <a href="{{ url_for('main.edit_topic', topic_id=topic.id) }}"
                           class="btn btn-sm btn-outline-primary"><span class="oi oi-pencil"></span> 编辑</a>
                    </td>{% endif %}
                </tr>
            {% endfor %}
        </table>
        <div class="page-footer">
            {{ render_pagination(pagination, align='center') }}
        </div>
    {% else %}
        <div class="tip text-center">
            <p class="text-muted">暂无内容</p>
        </div>
    {% endif %}
{% endblock %}

blogs/templates/user/topics_noticed.html
{% extends 'user/basic.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}已订阅的主题{% endblock %}

{% block user_content %}
    {% if notices %}
        <table class="table">
            <thead>
            <tr class="card-header bg-primary text-white">
                <th>主题</th>
                <th>组</th>
                <th><span class="oi oi-clock"></span></th>
                <th><span class="oi oi-wrench"></span> </th>
            </tr>
            </thead>
            {% for notice in notices %}
                <tr>
                    <td><a href="{{ url_for('main.show_topic', topic_id=notice.noticed_id) }}">
                        {{ notice.noticed.name }}</a><br>
                        由<a href="{{ url_for('user.index', username=notice.noticed.author.username) }}">
                            {{ notice.noticed.author.username }}</a>发布</td>
                    <td><a href="{{ url_for('main.show_group', group_id=notice.noticed.group_id) }}">
                        {{ notice.noticed.group.name }}</a></td>
                    <td class="text-muted">
                        {{ moment(notice.timestamp).format('llll')}}
                    </td>
                    <td>
                        <form method="post" action="{{ url_for('main.unnotice', topic_id=notice.noticed.id) }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <button type="submit" class="btn btn-outline-secondary btn-sm">
                                <span class="oi oi-x"></span> 取消订阅
                            </button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <div class="page-footer">
            {{ render_pagination(pagination, align='center') }}
        </div>
    {% else %}
        <div class="tip text-center">
            <p class="text-muted">暂无内容</p>
        </div>
    {% endif %}
{% endblock %}