blogs/models/tecon.py
# coding=utf-8
import os
from datetime import datetime
from flask import current_app

from blogs.extensions import db


class Photo(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    filename = db.Column(db.String(64))
    filename_s = db.Column(db.String(64))
    item_id = db.Column(db.Integer, db.ForeignKey('item.id'))

    item = db.relationship('Item')


@db.event.listens_for(Photo, 'after_delete', named=True)
def delete_photos(**kwargs):
    target = kwargs['target']
    for filename in [target.filename, target.filename_s]:
        path = os.path.join(current_app.config['TECON_PATH'], filename)
        if os.path.exists(path):                # not every filename map a unique file
            os.remove(path)


class Item(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(60))
    body = db.Column(db.Text)
    saved = db.Column(db.Boolean, default=False)
    series_id = db.Column(db.Integer, db.ForeignKey('series.id'))
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)

    photo = db.relationship('Photo', uselist=False, cascade='all')
    series = db.relationship('Series', back_populates='items')


class Series(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(10))

    items = db.relationship('Item', back_populates='series', cascade='all')

    @staticmethod
    def init_series():
        series_list = ['关于我们', '产品布局', '新闻中心']
        for name in series_list:
            series = Series.query.filter_by(name=name).first()
            if series is None:
                series = Series(name=name)
                db.session.add(series)
        db.session.commit()

blogs/forms/tecon.py
# coding=utf-8
from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField, StringField
from wtforms.validators import Length, DataRequired, ValidationError
from flask_ckeditor import CKEditorField
from flask_wtf.file import FileField, FileRequired, FileAllowed

from blogs.models.tecon import Item, Series


class ItemForm(FlaskForm):
    name = StringField('标题', validators=[DataRequired(), Length(1,60)])
    body = CKEditorField('', validators=[DataRequired(), Length(1, 2000)])
    series = SelectField('类别',  coerce=int)
    save = SubmitField('保存草稿')
    publish = SubmitField('发布')

    def __init__(self, *args, **kwargs):
        super(ItemForm, self).__init__(*args, **kwargs)
        self.series.choices = [(series.id, series.name)
                             for series in Series.query.order_by(Series.name).all()]

    def validate_name(self, field):
        if Item.query.filter_by(name=field.data).first():
            raise ValidationError('标题已存在。')


class EditItemForm(ItemForm):
    def __init__(self, item, *args, **kwargs):
        super(EditItemForm, self).__init__(*args, **kwargs)
        self.series.choices = [(series.id, series.name)
                               for series in Series.query.order_by(Series.name).all()]
        self.item = item

    def validate_name(self, field):
        if field.data != self.item.name and Item.query.filter_by(name=field.data).first():
            raise ValidationError('标题已存在。')


class UploadForm(FlaskForm):
    photo = FileField('', validators=[FileRequired(), FileAllowed(['jpg', 'jpeg', 'png', 'gif'])])
    submit = SubmitField('上传')

blogs/blueprints/auth.py
from flask import Blueprint, redirect, url_for, flash, render_template
from flask_login import current_user, login_required, login_user, logout_user, login_fresh, confirm_login

from blogs.settings import Operations
from blogs.forms.auth import LoginForm, ForgetPasswordForm, ResetPasswordForm, RegisterForm
from blogs.models.blogs import User
from blogs.extensions import db
from blogs.utils import generate_token, validate_token, redirect_back
from blogs.emails import send_reset_password_email, send_confirm_email

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is not None and user.validate_password(form.password.data):
            if login_user(user, form.remember_me.data):
                flash('登录成功.', 'info')
                return redirect_back()
            else:
                flash('你的账号已被封禁。', 'warning')
                return redirect(url_for('main.index'))
        flash('无效的邮箱或者密码.', 'warning')
    return render_template('auth/login.html', form=form)


@auth_bp.route('/forget-password', methods=['GET', 'POST'])
def forget_password():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = ForgetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user:
            token = generate_token(user=user, operation=Operations.RESET_PASSWORD)
            send_reset_password_email(user=user, token=token)
            flash('重设密码邮件已发送，请查看你的邮箱。', 'info')
            return redirect(url_for('.login'))
        flash('无效的邮箱.', 'warning')
        form.email.data = ""
        return redirect(url_for('.forget_password'))
    return render_template('auth/reset_password.html', form=form)


@auth_bp.route('/reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is None:
            return redirect(url_for('main.index'))
        if validate_token(user=user, token=token, operation=Operations.RESET_PASSWORD,
                          new_password=form.password.data):
            flash('密码已更新', 'success')
            form.email.data = ""
            return redirect(url_for('.login'))
        else:
            flash('链接无效或者超时。', 'danger')
            return redirect(url_for('.forget_password'))
    return render_template('auth/reset_password.html', form=form)


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('成功登出', 'info')
    return redirect(url_for('main.index'))


@auth_bp.route('/register', methods=['POST', 'GET'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = RegisterForm()
    if form.validate_on_submit():
        username = form.username.data
        name = form.name.data
        email = form.email.data.lower()  # 小写处理
        password = form.password.data
        company = form.company.data
        user = User(username=username, email=email, company=company, name=name)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        send_confirm_email(user=user)
        flash('确认邮件已发送给系统管理员，请等待管理员确认', 'info')
        return redirect(url_for('.login'))
    return render_template('auth/register.html', form=form)


@auth_bp.route('/re-authenticate', methods=['GET', 'POST'])
@login_required
def re_authenticate():
    if login_fresh():
        return redirect(url_for('main.index'))

    form = LoginForm()
    if form.validate_on_submit() and current_user.validate_password(form.password.data):
        confirm_login()
        return redirect_back()
    return render_template('auth/login.html', form=form)

blogs/blueprints/tecon.py
# coding=utf-8
from flask import Blueprint, render_template, request, redirect, current_app, flash, url_for, send_from_directory
from flask_login import login_required
import os
import PIL
from PIL import Image

from blogs.decorators import permission_required
from blogs.models.tecon import Item, Series, Photo
from blogs.forms.tecon import ItemForm, EditItemForm, UploadForm
from blogs.extensions import db
from blogs.utils import rename_image

view_bp = Blueprint('tecon', __name__)


def resize_image(image, filename, base_width):
    filename, ext = os.path.splitext(filename)
    img = Image.open(image)
    if img.size[0] <= base_width:
        return filename + ext
    w_percent = (base_width / float(img.size[0]))
    h_size = int((float(img.size[1]) * float(w_percent)))
    img = img.resize((base_width, h_size), PIL.Image.ANTIALIAS)

    filename += current_app.config['PHOTO_SUFFIX'][base_width] + ext
    img.save(os.path.join(current_app.config['TECON_PATH'], filename), optimize=True, quality=85)
    return filename


@view_bp.route('/')
def index():
    newses = Item.query.filter_by(saved=False, series_id=3).order_by(Item.timestamp.desc()).limit(3)
    return render_template('tecon/index.html', newses=newses)


@view_bp.route('/item/<int:item_id>')
def show_item(item_id):
    item = Item.query.get_or_404(item_id)
    return render_template('tecon/item.html', item=item)


@view_bp.route('/newses')
def show_newses():
    series = Series.query.filter(Series.name=='新闻中心').first()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['NEWS_PER_PAGE']
    pagination = Item.query.with_parent(series).filter_by(saved=False).order_by(Item.timestamp.desc()).\
        paginate(page, per_page)
    newses = pagination.items
    return render_template('tecon/newses.html', newses=newses, pagination=pagination)


@view_bp.route('/new_item', methods=['GET', 'POST'])
@login_required
@permission_required('PUBLICITY')
def new_item():
    form = ItemForm()
    if form.validate_on_submit():
        name = form.name.data
        body = form.body.data
        series_id = form.series.data
        item = Item(name=name, body=body, series_id=series_id)
        db.session.add(item)
        if form.save.data:
            item.saved = True
            db.session.commit()
            flash('已保存', 'info')
            return redirect(url_for('.manage'))
        if form.publish.data:
            db.session.commit()
            flash('新项目已发布', 'success')
            return redirect(url_for('.upload', item_id=item.id))
    return render_template('tecon/item_form.html', form=form)


@view_bp.route('/edit_item/<int:item_id>', methods=['GET', 'POST'])
@login_required
@permission_required('PUBLICITY')
def edit_item(item_id):
    item = Item.query.get_or_404(item_id)
    form = EditItemForm(item=item)
    if form.validate_on_submit():
        item.name = form.name.data
        item.body = form.body.data
        item.series_id = form.series.data
        if form.save.data:
            item.saved = True
            db.session.commit()
            flash('已保存', 'info')
            return redirect(url_for('.manage'))
        if form.publish.data:
            item.saved = False
            db.session.commit()
            flash('新项目已发布', 'success')
            return redirect(url_for('.manage'))
    form.name.data = item.name
    form.body.data = item.body
    form.series.data = item.series_id
    return render_template('tecon/edit_item.html', form=form, item=item)


@view_bp.route('/delete_item/<int:item_id>', methods=['POST'])
@login_required
@permission_required('PUBLICITY')
def delete_item(item_id):
    item = Item.query.get_or_404(item_id)
    db.session.delete(item)
    db.session.commit()
    flash('已删除', 'success')
    return redirect(url_for('.manage'))


@view_bp.route('/manage')
@login_required
@permission_required('PUBLICITY')
def manage():
    draft_count = Item.query.filter_by(saved=True).count()
    news_count = Item.query.filter_by(saved=False, series_id=3).count()
    intro_count = Item.query.filter_by(saved=False, series_id=1).count()
    product_count = Item.query.filter_by(saved=False, series_id=2).count()
    return render_template('tecon/manage.html', draft_count=draft_count, news_count=news_count, intro_count=intro_count,
                           product_count=product_count)


@view_bp.route('/manage_list')
@login_required
@permission_required('PUBLICITY')
def manage_list():
    filter_rule = request.args.get('filter', 'news')  #'news', 'intro', 'product'， 'draft'
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['MANAGE_NEWS_PER_PAGE']
    items = None
    series = None
    if filter_rule == 'news':
        series = Series.query.get(3)
        items = Item.query.with_parent(series).filter_by(saved=False)
    elif filter_rule == 'intro':
        series = Series.query.get(1)
        items = Item.query.with_parent(series).filter_by(saved=False)
    elif filter_rule == 'product':
        series = Series.query.get(2)
        items = Item.query.with_parent(series).filter_by(saved=False)
    elif filter_rule == 'draft':
        items = Item.query.filter_by(saved=True)
    pagination = items.order_by(Item.timestamp.desc()).paginate(page, per_page)
    items = pagination.items
    return render_template('tecon/list.html', items=items, pagination=pagination, series=series)


@view_bp.route('/uploads/<path:filename>')
def get_image(filename):
    return send_from_directory(current_app.config['TECON_PATH'], filename)


@view_bp.route('/upload/<int:item_id>', methods=['POST', 'GET'])
@login_required
@permission_required('PUBLICITY')
def upload(item_id):
    item = Item.query.get_or_404(item_id)
    form = UploadForm()
    if form.validate_on_submit():
        if item.photo:
            db.session.delete(item.photo)
            db.session.commit()
        f = form.photo.data
        filename = rename_image(f.filename)
        f.save(os.path.join(current_app.config['TECON_PATH'], filename))
        filename_s = resize_image(f, filename, current_app.config['PHOTO_SIZE']['small'])
        photo = Photo(filename=filename,
                      filename_s=filename_s,
                      item_id=item_id)
        db.session.add(photo)
        db.session.commit()
        flash('图片已上传', 'success')
        return redirect(url_for('.show_item', item_id=item_id))
    return render_template('tecon/upload.html', item=item, form=form)

blogs/templates/tecon/base.html
{% from 'bootstrap/nav.html' import render_nav_item %}

<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block head %}
        <title>{% block title %}{% endblock %} - Tecon</title>
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
        {% block styles %}
            <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='open-iconic/font/css/open-iconic-bootstrap.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/tecon.css') }}">
        {% endblock styles %}
    {% endblock head %}
</head>
<body>

{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('tecon.index') }}">
                <img src="{{ url_for('static', filename='favicon.ico') }}" alt="Tecon">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                    aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <div class="navbar-nav mr-auto">
                    {{ render_nav_item('tecon.index', '主页') }}
                </div>
                <div class="navbar-nav mr-auto">
                    <div class="dropdown nav-item">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-expanded="false">
                            关于我们<span class="caret"></span>
                        </a>
                        <div class="dropdown-menu" role="menu">
                            {% for item in introduces  %}
                                <a class="dropdown-item" href="{{ url_for('tecon.show_item', item_id=item.id )}}">
                                    {{ item.name }}
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="navbar-nav mr-auto">
                    <div class="dropdown nav-item">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-expanded="false">
                            产品布局<span class="caret"></span>
                        </a>
                        <div class="dropdown-menu" role="menu">
                            {% for item in products  %}
                                <a class="dropdown-item" href="{{ url_for('tecon.show_item', item_id=item.id )}}">
                                    {{ item.name }}
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="navbar-nav mr-auto">
                    {{ render_nav_item('tecon.show_newses', '新闻中心')}}
                </div>
                {% if current_user.can('PUBLICITY') %}
                    <div class="navbar-nav ml-auto">
                        <a class="nav-item" href="{{ url_for('tecon.manage')}}">
                            <span class="oi oi-dashboard text-light"></span></a>
                    </div>
                {% endif %}
            </div>
        </div>
    </nav>
{% endblock %}

<main>
    {% block img %}{% endblock %}
    <div class="container">
        {% for message in get_flashed_messages(with_categories=True) %}
            <div class="alert alert-{{ message[0] }}">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message[1] }}
            </div>
        {% endfor %}
        {% block content %}{% endblock %}
        <div class="row bg-light page-footer">
            <div class="col-sm-7 table-auto">
                <table class="table inline list-table">
                    <tr><th><h4>关于我们</h4></th></tr>
                    {% for item in introduces %}
                        <tr>
                            <td><a href="{{ url_for('tecon.show_item', item_id=item.id )}}" class="text-dark">
                                <h6>{{ item.name }}</h6></a></td>
                        </tr>
                    {% endfor %}
                </table>
                <table class="table inline list-table">
                    <tr><th><h4>产品布局</h4></th></tr>
                    {% for item in products %}
                        <tr>
                            <td><a href="{{ url_for('tecon.show_item', item_id=item.id )}}" class="text-dark">
                                <h6>{{ item.name }}</h6></a></td>
                        </tr>
                    {% endfor %}
                </table>
                <table class="table inline list-table"><tr><th>
                    <a href="{{ url_for('tecon.show_newses')}}" class="text-dark"><h4>新闻中心</h4></a>
                </th></tr></table>
            </div>
            <div class="col-sm-5">
                <img alt="Tecon Logo" src="{{ url_for('static', filename='imgs/logo.png') }}" height="300px">
            </div>
        </div>
        <footer>
            <p class="float-left">
                <small> &copy; Tecon 深圳泰科晶显科技有限公司</small>
            </p>
            <p class="float-right text-white">
                <small>
                    {% if current_user.is_authenticated %}
                        <a href="{{ url_for('auth.logout', next=request.full_path) }}">退出</a>
                    {% else %}
                        <a href="{{ url_for('auth.login', next=request.full_path) }}">登录</a>
                    {% endif %}
                </small>
            </p>
        </footer>
    </div>
</main>

{% block scripts %}
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    {{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
    {{ moment.locale('zh-cn') }}
    <script src="{{ url_for('static', filename='js/tecon.js') }}"></script>
{% endblock %}

</body>
</html>

blogs/templates/tecon/edit_item.html
{% extends 'tecon/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}编辑{{ item.name }}{% endblock %}

{% block content %}
    <div class="card w-100 bg-light">
        <h4 class="card-header">编辑{{ item.name }}</h4>
        {% if item.photo %}
            <a href="{{ url_for('tecon.upload', item_id=item.id)}}">
                <img src="{{ url_for('tecon.get_image', filename=item.photo.filename)}}" class="large_photo"></a>
        {% endif %}
        <div class="card-body">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript" src="{{ url_for('static', filename='ckeditor/ckeditor.js') }}"></script>
{% endblock %}

blogs/templates/tecon/index.html
{% extends 'tecon/base.html' %}
{% from 'tecon/macros.html' import news_card with context %}

{% block title %}泰科{% endblock %}

{% block img %}
    <img src="{{ url_for('static', filename='imgs/home.jpg') }}">
{% endblock %}

{% block content %}
    <h2 class="float-left">产业布局</h2>
    <h4 class="text-muted">Industrial Layout</h4>
    <hr class="up-10">
    <div class="row">
    {% for product in products %}
        <div class="col-sm-4 little-thumbnail">
            <a href="{{ url_for('tecon.show_item', item_id=product.id) }}">
                <img src="{{ url_for('tecon.get_image', filename=product.photo.filename_s) }}"
                     alt="{{ product.name }}"></a>
        </div>
    {% endfor %}
    </div>
    <h2 class="float-left">关于我们</h2>
    <h4 class="text-muted strong">Abort Us</h4>
    <hr class="up-10">
    <div class="row">
    {% for intro in introduces %}
        <div class="col-sm-4 little-thumbnail">
            <a href="{{ url_for('tecon.show_item', item_id=intro.id) }}">
                <img src="{{ url_for('tecon.get_image', filename=intro.photo.filename_s) }}" alt="{{ intro.name }}">
            </a>
        </div>
    {% endfor %}
    </div>
    <h2 class="float-left">新闻中心</h2>
    <h4 class="text-muted">News</h4>
    <hr class="up-10">
    <div class="row">
        {% for news in newses %}
            <div class="col-sm-4">
                {{ news_card(news) }}
            </div>
        {% endfor %}
    </div>
{% endblock %}

blogs/templates/tecon/item.html
{% extends 'tecon/base.html' %}

{% block title %} {{ item.name }}{% endblock %}

{% block img %}
<a href="{% if current_user.can('PUBLICITY') %}{{ url_for('tecon.upload', item_id=item.id)}}{% else %}#{% endif %}">
    <img src="{{ url_for('tecon.get_image', filename=item.photo.filename)}}" class="large_photo"></a>
{% endblock %}

{% block content %}
    <button type="button" class="btn btn-primary btn-sm float-right" data-toggle="modal" data-target=".introLinkModal">
        分享</button>
    {% if current_user.can('PUBLICITY') %}
        <a href="{{ url_for('tecon.edit_item', item_id=item.id)}}" class="float-right btn btn-success btn-sm">编辑</a>
    {% endif %}
    <h3 class="text-center">{{ item.name }}</h3>
    {% if item.series_id == 3 %}
        <p class="float-right text-muted">{{ moment(item.timestamp).format('LLL')}}</p>
    {% endif %}
    <br>
    {{ item.body|safe }}
    <div class="modal fade introLinkModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel"
                 aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="mySmallModalLabel">链接地址</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <input type="text" class="form-control" value="{{ url_for('tecon.show_item',
                            item_id=item.id, _external=True) }}" readonly>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blogs/templates/tecon/item_form.html
{% extends 'tecon/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}新增项目{% endblock %}

{% block content %}
    <div class="card w-100 bg-light">
        <h4 class="card-header">新增项目</h4>
        <div class="card-body">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript" src="{{ url_for('static', filename='ckeditor/ckeditor.js') }}"></script>
{% endblock %}

blogs/templates/tecon/list.html
{% extends 'tecon/base.html' %}

{% block title %}后台管理{% endblock %}

{% block content %}
    <div class="nav nav-pills" role="tablist">
        <a class="nav-item nav-link {% if request.args.get('filter')=='news' %}active{% endif %}"
           href="{{ url_for('tecon.manage_list', filter='news') }}">
            新闻中心
        </a>
        <a class="nav-item nav-link {% if request.args.get('filter') == 'intro' %}active{% endif %}"
           href="{{ url_for('tecon.manage_list', filter='intro') }}">
            公司简介
        </a>
        <a class="nav-item nav-link {% if request.args.get('filter') == 'product' %}active{% endif %}"
           href="{{ url_for('tecon.manage_list', filter='product') }}">
            产品布局
        </a>
        <a class="nav-item nav-link {% if request.args.get('filter') == 'draft' %}active{% endif %}"
           href="{{ url_for('tecon.manage_list', filter='draft') }}">
            草稿
        </a>
    </div>
    {% if series %}
        <h3><strong>{{ series.name }}</strong>列表</h3>
    {% else %}
        <h3>草稿列表</h3>
    {% endif %}
    <table class="table">
        <thead>
        <tr class="bg-primary text-white">
            <th width="20%">标题</th>
            <th>图片</th>
            <th width="50%">内容</th>
            {% if request.args.get('filter')=='news' %}<th width="100%"><span class="oi oi-clock"></span></th>{% endif %}
            <th><span class="oi oi-wrench"></span></th>
        </tr>
        </thead>
        {% for item in items %}
            <tr>
                <td><a href="{{ url_for('tecon.show_item', item_id=item.id)}}">{{ item.name }}</a></td>
                <td><a href="{{ url_for('tecon.upload', item_id=item.id)}}">
                        <img src="{{ url_for('tecon.get_image', filename=item.photo.filename_s)}}"></a></td>
                <td>{{ item.body|striptags|truncate(180,ture,'......') }}</td>
                {% if request.args.get('filter')=='news' %}
                    <td>{{ moment(item.timestamp).format('LLL') }}</td>
                {% endif %}
                <td><form action="{{ url_for('tecon.delete_item', item_id=item.id) }}" method="post" class="inline">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                        <button type="submit" class="btn btn-outline-danger btn-sm"
                                onclick="return confirm('确定删除此项目吗？')">删除</button>
                    </form>
                    <a href="{{ url_for('tecon.edit_item', item_id=item.id)}}" class="btn btn-outline-primary btn-sm">
                        编辑</a>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

blogs/templates/tecon/macros.html
{% macro news_card(news) %}
    <div class="card border-light">
        <img src="{{ url_for('tecon.get_image', filename=news.photo.filename_s)}}" class="photo-thumbnail">
        <h5 class="card-title"><a href="{{ url_for('tecon.show_item', item_id=news.id) }}">
            {{ news.name }}</a></h5>
        {% if current_user.can('PUBLICITY') %}
            <div class="dropdown nav-item">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                   aria-expanded="false">
                    <span class="oi oi-ellipses"></span>
                </a>
                <div class="dropdown-menu" role="menu">
                    <a href="{{ url_for('tecon.edit_item', item_id=news.id)}}" class="dropdown-item text-success">编辑</a>
                    <form method="post" action="{{ url_for('tecon.delete_item', item_id=news.id)}}">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                        <button type="submit" class="dropdown-item text-danger"
                                onclick="return confirm('确定删除吗？')">删除</button>
                    </form>
                </div>
            </div>
        {% endif %}
        <p class="card-text">{{ news.body|striptags|truncate(150,ture,'......') }}
            <a href="{{ url_for('tecon.show_item', item_id=news.id) }}">查看更多</a>
        </p>
        <hr>
        <p class="text-muted text-center">
            <small>{{ moment(news.timestamp).format('LLL')}}</small>
        </p>
    </div>
{% endmacro %}

blogs/templates/tecon/upload.html
{% extends 'tecon/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %} {{ item.name }}{% endblock %}

{% block content %}
    {% if item.photo %}
        <img src="{{ url_for('tecon.get_image', filename=item.photo.filename)}}" class="large_photo">
    {% endif %}
    <div class="card w-100 bg-light">
        <h4 class="card-header">上传图片</h4>
        <div class="card-body">
            {{ render_form(form, extra_classes='col-6') }}
            <small class="text-muted">你的图片必须小于3M，且仅允许jpg、jpeg、png和gif格式图片。</small>
        </div>
    </div>
{% endblock %}