blogs/blueprints/ajax.py
from flask import Blueprint, jsonify, render_template
from flask_login import current_user

from blogs.models.blogs import User, Notification

ajax_bp = Blueprint('ajax', __name__)


@ajax_bp.route('/get_profile/<int:user_id>')
def get_profile(user_id):
    if not current_user.is_authenticated:
        return jsonify(message='请先登录'), 403
    user = User.query.get_or_404(user_id)
    return render_template('main/profile_popup.html', user=user)


@ajax_bp.route('/notifications-count')
def notifications_count():
    if not current_user.is_authenticated:
        return jsonify(message='请先登录'), 403

    count = Notification.query.with_parent(current_user).filter_by(is_read=False).count()
    return jsonify(count=count)

blogs/blueprints/auth.py
from flask import Blueprint, redirect, url_for, flash, render_template
from flask_login import current_user, login_required, login_user, logout_user, login_fresh, confirm_login

from blogs.settings import Operations
from blogs.forms.auth import LoginForm, ForgetPasswordForm, ResetPasswordForm, RegisterForm
from blogs.models.blogs import User
from blogs.extensions import db
from blogs.utils import generate_token, validate_token, redirect_back
from blogs.emails import send_reset_password_email, send_confirm_email

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is not None and user.validate_password(form.password.data):
            if login_user(user, form.remember_me.data):
                flash('登录成功.', 'info')
                return redirect_back()
            else:
                flash('你的账号已被封禁。', 'warning')
                return redirect(url_for('main.index'))
        flash('无效的邮箱或者密码.', 'warning')
    return render_template('auth/login.html', form=form)


@auth_bp.route('/forget-password', methods=['GET', 'POST'])
def forget_password():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = ForgetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user:
            token = generate_token(user=user, operation=Operations.RESET_PASSWORD)
            send_reset_password_email(user=user, token=token)
            flash('重设密码邮件已发送，请查看你的邮箱。', 'info')
            return redirect(url_for('.login'))
        flash('无效的邮箱.', 'warning')
        form.email.data = ""
        return redirect(url_for('.forget_password'))
    return render_template('auth/reset_password.html', form=form)


@auth_bp.route('/reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is None:
            return redirect(url_for('main.index'))
        if validate_token(user=user, token=token, operation=Operations.RESET_PASSWORD,
                          new_password=form.password.data):
            flash('密码已更新', 'success')
            form.email.data = ""
            return redirect(url_for('.login'))
        else:
            flash('链接无效或者超时。', 'danger')
            return redirect(url_for('.forget_password'))
    return render_template('auth/reset_password.html', form=form)


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('成功登出', 'info')
    return redirect(url_for('main.index'))


@auth_bp.route('/register', methods=['POST', 'GET'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = RegisterForm()
    if form.validate_on_submit():
        username = form.username.data
        name = form.name.data
        email = form.email.data.lower()  # 小写处理
        password = form.password.data
        company = form.company.data
        user = User(username=username, email=email, company=company, name=name)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        send_confirm_email(user=user)
        flash('确认邮件已发送给系统管理员，请等待管理员确认', 'info')
        return redirect(url_for('.login'))
    return render_template('auth/register.html', form=form)


@auth_bp.route('/re-authenticate', methods=['GET', 'POST'])
@login_required
def re_authenticate():
    if login_fresh():
        return redirect(url_for('main.index'))

    form = LoginForm()
    if form.validate_on_submit() and current_user.validate_password(form.password.data):
        confirm_login()
        return redirect_back()
    return render_template('auth/login.html', form=form)

blogs/blueprints/main.py
from flask import render_template, Blueprint, send_from_directory, current_app, request, redirect, url_for, abort, flash
from flask_login import current_user, login_required
import os
import time
from flask_ckeditor import upload_success, upload_fail
import uuid

from blogs.models.blogs import File, Post, Group, User, Notification, Topic, Read
from blogs.extensions import db
from blogs.forms.main import PostForm
from blogs.utils import redirect_back, resize_image, rename_image
from blogs.noticifations import push_post_notification, push_collect_notification, push_notice_notification, \
    push_max_reported_post_notification, push_max_reported_topic_notification
from blogs.decorators import permission_required, confirm_required
from blogs.emails import send_new_post_email
from blogs.forms.admin import MigrateForm

main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index():
    all_groups = Group.query.filter_by(status_id=4).all()
    apart_groups = Group.query.filter_by(status_id=3).all()
    limit_groups = Group.query.filter_by(status_id=2).all()
    member_groups = Group.query.filter_by(status_id=1).all()
    return render_template('main/index.html', all_groups=all_groups, limit_groups=limit_groups,
                           groups=apart_groups, member_groups=member_groups)


@main_bp.route('/new_topic/<int:group_id>', methods=['POST', 'GET'])
@login_required
@confirm_required
def new_topic(group_id):
    if group_id == 3:
        abort(403)
    group = Group.query.get_or_404(group_id)
    if group.status_id == 1 and not current_user.can('MEMBER'):
        abort(403)

    if group.status_id == 2 and not current_user.can('MEMBER'):
        abort(403)

    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data
        topic = Topic(name=title, body=body, group_id=group_id, author=current_user._get_current_object())
        db.session.add(topic)
        if form.publish.data:
            current_user.read(topic)  # 标记自己发表的文章为已读
            db.session.commit()
            if form.notice.data:
                current_user.notice(topic)
            flash('主题已发表', 'success')
            return redirect(url_for('main.show_topic', topic_id=topic.id))
        elif form.save.data:
            topic.saved = True
            db.session.commit()
            flash('主题已保存', 'success')
            return redirect(url_for('user.draft_topic'))
        elif form.save1.data:
            topic.saved = True
            db.session.commit()
            flash('请上传附件', 'info')
            return redirect(url_for('.upload_topic', topic_id=topic.id))
    return render_template('main/new_topic.html', form=form, group=group)


@main_bp.route('/show_topic/<int:topic_id>')
def show_topic(topic_id):
    topic = Topic.query.get_or_404(topic_id)
    topic.read_time += 1
    db.session.commit()
    if topic.saved and current_user != topic.author and not current_user.can('MODERATE'):
        abort(404)
    if not current_user.is_authenticated and topic.group.status_id != 4:
        flash('请登录', 'info')
        return redirect(url_for('auth.login'))

    if current_user.is_authenticated and not current_user.confirmed and topic.group.status_id != 4:
        flash('请等待管理员确认您的账户', 'warning')
        return redirect(url_for('main.index'))

    if not current_user.can('MEMBER') and topic.group.status_id == 1:
        abort(403)

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['POST_PER_PAGE']
    pagination = Post.query.with_parent(topic).filter_by(saved=False).\
        order_by(Post.timestamp.asc()).paginate(page, per_page)
    posts = pagination.items
    if current_user.is_authenticated:
        current_user.read(topic)
    form = MigrateForm()
    return render_template('main/show_topic.html', topic=topic, posts=posts, pagination=pagination, form=form)


@main_bp.route('/new_post/<int:topic_id>', methods=['POST', 'GET'])
@login_required
@confirm_required
def new_post(topic_id):
    topic = Topic.query.get_or_404(topic_id)
    if topic.group.status_id == 1 and not current_user.can('MEMBER'):
        abort(403)
    if topic.group.status_id == 2 and not current_user.can('MEMBER'):
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data
        post = Post(title=title, body=body, topic=topic, author=current_user._get_current_object())
        db.session.add(post)
        if form.publish.data:
            db.session.commit()
            if topic.receivers:
                for notice in topic.receivers:
                    send_new_post_email(receiver=notice.receiver, topic=topic, user=current_user)
            if form.notice.data:
                current_user.notice(topic)
            if current_user != topic.author and topic.author.receive_post_notification:
                push_post_notification(post=post, receiver=topic.author)
            flash('帖子已发表', 'success')
            return redirect(url_for('main.show_post', post_id=post.id))
        elif form.save.data:
            post.saved = True
            db.session.commit()
            flash('帖子已保存', 'success')
            return redirect(url_for('user.draft_post'))
        elif form.save1.data:
            post.saved = True
            db.session.commit()
            flash('请上传附件', 'info')
            return redirect(url_for('.upload_post', post_id=post.id))
    form.title.data = 'Re:'+topic.name
    return render_template('main/new_post.html', form=form, topic=topic)


@main_bp.route('/uploads/<path:filename>')
def get_file(filename):
    return send_from_directory(current_app.config['UPLOAD_PATH'], filename)


@main_bp.route('/upload', methods=['POST'])
def upload():
    f = request.files.get('upload')  # 获取上传图片文件对象
    extension = f.filename.split('.')[1].lower()
    if extension not in ['jpg', 'gif', 'png', 'jpeg']:  # 验证文件类型示例
        return upload_fail(message='只能上传图片！')  # 返回upload_fail调用
    filename = uuid.uuid4().hex + '.' + extension
    if os.path.exists(os.path.join(current_app.config['UPLOAD_PATH'], filename)):
        filename = rename_image(filename)
    f.save(os.path.join(current_app.config['UPLOAD_PATH'], filename))
    resize_image(request.files['upload'], filename, current_app.config['PHOTO_SIZE']['medium'])
    url = url_for('.get_file', filename=filename)
    return upload_success(url, filename) # 返回upload_success调用


@main_bp.route('/post/<int:post_id>', methods=['POST', 'GET'])
def show_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.saved and current_user != post.author and not current_user.can('MODERATE'):
        abort(404)
    if not current_user.is_authenticated and post.topic.group.status_id != 4:
        flash('请登录', 'info')
        return redirect(url_for('auth.login'))

    if current_user.is_authenticated and not current_user.confirmed and post.topic.group.status_id != 4:
        flash('请等待管理员确认您的账户', 'warning')
        return redirect(url_for('main.index'))
    if not current_user.can('MEMBER') and post.topic.group.status_id == 1:
        abort(403)
    return render_template('main/post.html', post=post)


@main_bp.route('/avatars/<path:filename>')
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@main_bp.route('/post/<int:post_id>/d', methods=['POST'])
@login_required
@confirm_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user != post.author and current_user != post.topic.group.admin and not current_user.can('MODERATE'):
        abort(403)

    db.session.delete(post)
    db.session.commit()
    flash('成功删除帖子', 'success')
    return redirect_back()


@main_bp.route('/topic/<int:topic_id>/delete', methods=['POST'])
@login_required
@confirm_required
def delete_topic(topic_id):
    topic = Topic.query.get_or_404(topic_id)
    if current_user != topic.group.admin and not current_user.can('MODERATE') and current_user != topic.author:
        abort(403)
    db.session.delete(topic)
    db.session.commit()
    flash('删除主题成功', 'success')
    return redirect_back()


@main_bp.route('/notifications')
@login_required
def show_notifications():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['NOTIFICATION_PER_PAGE']
    notifications = Notification.query.with_parent(current_user)
    filter_rule = request.args.get('filter')
    if filter_rule == 'unread':
        notifications = notifications.filter_by(is_read=False)

    pagination = notifications.order_by(Notification.timestamp.desc()).paginate(page, per_page)
    notifications = pagination.items
    return render_template('main/notifications.html', pagination=pagination, notifications=notifications)


@main_bp.route('/notification/read/<int:notification_id>', methods=['POST'])
@login_required
def read_notification(notification_id):
    notification = Notification.query.get_or_404(notification_id)
    if current_user != notification.receiver:
        abort(403)

    notification.is_read = True
    db.session.commit()
    flash('通知已读。', 'success')
    return redirect(url_for('.show_notifications'))


@main_bp.route('/notifications/read/all', methods=['POST'])
@login_required
def read_all_notification():
    for notification in current_user.notifications:
        notification.is_read = True
    db.session.commit()
    flash('所有通知已读', 'success')
    return redirect(url_for('.show_notifications'))


@main_bp.route('/reply/post/<int:replied_id>', methods=['POST', 'GET'])
@login_required
@confirm_required
def reply_post(replied_id):
    replied = Post.query.get_or_404(replied_id)
    if replied.topic.group.status_id == 1 and not current_user.can('MEMBER'):
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data
        author = current_user._get_current_object()
        post = Post(body=body,

blogs/templates/base.html
{% from 'bootstrap/nav.html' import render_nav_item %}

<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block head %}
        <title>{% block title %}{% endblock %} - BBS</title>
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
        {% block styles %}
            <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='open-iconic/font/css/open-iconic-bootstrap.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css">
        {% endblock styles %}
    {% endblock head %}
</head>
<body>
<!--{% block img %}
    <a href="{{ url_for('main.index')}}">
        <img src="{{ url_for('static', filename='imgs/home.jpg') }}">
    </a>
{% endblock %}-->

{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('main.index') }}">
                <h3 class="text-blue">深圳泰科晶显科技有限公司</h3>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                    aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <div class="navbar-nav mr-auto">
                    {{ render_nav_item('main.index', '论坛首页') }}
                </div>
                <div class="navbar-nav ml-auto">
                    <form class="form-inline my-2 my-lg-0" action="{{ url_for('main.search') }}">
                        <input type="text" name="q" class="form-control mr-sm-1" placeholder="请输入搜索关键字"
                               required>
                        <button class="btn btn-light my-2 my-sm-0 btn-sm" type="submit">
                            <span class="oi oi-magnifying-glass"></span>
                        </button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    </form>
                    {% if current_user.is_authenticated %}
                        <div class="dropdown nav-item">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-expanded="false">
                                <img class="avatar-xs"
                                     src="{{ url_for('main.get_avatar', filename=current_user.avatar_s) }}">
                                <span class="caret"></span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" role="menu">
                                <h5 class="dropdown-header">{{ current_user.username }}</h5>
                                <a class="dropdown-item" href="{{ url_for('user.index', username=current_user.username) }}">
                                    <span class="oi oi-person"></span> 我的主页
                                </a>
                                {% if current_user.can('MODERATE') %}
                                    <a class="dropdown-item" href="{{ url_for('admin.index', filter='confirmed') }}">
                                        <span class="oi oi-dashboard"></span> 管理员主页
                                    </a>
                                {% endif %}
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{{ url_for('user.edit_profile') }}">
                                    <span class="oi oi-cog"></span> 设置
                                </a>
                                <a class="dropdown-item" href="{{ url_for('auth.logout') }}">
                                    <span class="oi oi-power-standby"></span> 退出
                                </a>
                            </div>
                        </div>
                    {% else %}
                        <a href="{{ url_for('auth.login') }}">
                            <span class="oi oi-power-standby text-dark">登录</span>
                        </a>&nbsp;&nbsp;
                        <a href="{{ url_for('auth.register') }}">
                            <span class="oi oi-pencil text-dark">注册</span>
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
{% endblock %}

<main>
    <div class="container">
        {% block header %}{% endblock %}
        {% for message in get_flashed_messages(with_categories=True) %}
            <div class="alert alert-{{ message[0] }}">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message[1] }}
            </div>
        {% endfor %}
        {% block content %}{% endblock %}
        <!-- delete confirm modal -->
        {% if current_user.is_authenticated %}
            <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                        </div>
                        <div class="modal-body">
                            <p>确认删除这项吗？</p>
                        </div>
                        <div class="modal-footer">
                            <form class="delete-form" action="" method="post">
                                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                                <button class="btn btn-danger btn-confirm" type="submit">删除</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
        {% block footer %}
            <div class="page-footer" id="bottom"></div>
            <footer>
                <p class="float-left">
                    <small>
                        <a href="http://120.78.128.55/tecon" title="Tecon">深圳泰科晶显科技有限公司</a>
                    </small>
                </p>
                <p class="float-right">
                    <small>Enjoy every wonderful moment.</small>
                </p>
            </footer>
        {% endblock %}
    </div>
</main>
<div id="toast"></div>

{% block scripts %}
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    {{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
    {{ moment.locale('zh-cn') }}
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    <script type="text/javascript">
        var csrf_token = "{{ csrf_token() }}";
        {% if current_user.is_authenticated %}
            var is_authenticated = true;
        {% else %}
            var is_authenticated = false;
        {% endif %}
    </script>
{% endblock %}
</body>
</html>

blogs/templates/macros.html
{% macro file_area(file) %}
    <div class="fileMessage">
        <a href="{{ url_for('main.get_file', filename=file.filename)}}">{{ file.filename }}</a><br>
        <p class="small">
            <a href="{{ url_for('main.get_file', filename=file.filename)}}" class="text-dark"
              download="{{ filename}}"><span class="oi oi-data-transfer-download"></span>下载</a>&nbsp;&nbsp;
            <a href="{{ url_for('main.get_file', filename=file.filename)}}" target="_blank" class="text-dark">
                <span class="oi oi-list"></span>详情</a>&nbsp;&nbsp;
            {% if current_user==file.post.author or current_user.can('MODERATE') or current_user==file.topic.author%}
                <a data-toggle="modal" data-target="#confirm-delete" href="#!"
                    data-href="{{ url_for('main.delete_file', file_id=file.id, next=request.full_path) }}" class="text-danger">
                    <small class="oi oi-circle-x"></small>删除</a>
            {% endif %}
        </p>
        <div class="clear_float"></div>
    </div>
{% endmacro %}

{% macro file_display(file) %}
    {% if file.filename.rsplit('.', 1)[1] in ['jpg', 'png', 'jpeg', 'gif', 'PNG', 'bmp'] %}
        {{ photo_card(file) }}
    {% elif file.filename.rsplit('.', 1)[1] in ['txt', 'log'] %}
        <div>
            <img src="{{ url_for('static', filename='imgs/txt.png') }}" class="float-left">
            {{ file_area(file)}}
        </div>
    {% elif file.filename.rsplit('.', 1)[1] in ['xlsx', 'xls'] %}
        <div>
            <img src="{{ url_for('static', filename='imgs/xlsx.png') }}" class="float-left">
            {{ file_area(file) }}
        </div>
    {% elif file.filename.rsplit('.', 1)[1] in ['docx', 'doc'] %}
        <div>
            <img src="{{ url_for('static', filename='imgs/docx.png') }}" class="float-left">
            {{ file_area(file) }}
        </div>
    {% elif file.filename.rsplit('.', 1)[1] in ['pdf'] %}
        <div>
            <img src="{{ url_for('static', filename='imgs/pdf.png') }}" class="float-left">
            {{ file_area(file) }}
        </div>
    {% elif file.filename.rsplit('.', 1)[1] in ['rar', 'zip', 'arj', 'gz', 'z'] %}
        <div>
            <img src="{{ url_for('static', filename='imgs/rar.png') }}" class="float-left">
            {{ file_area(file) }}
        </div>
    {% else %}
        <div>
            <img src="{{ url_for('static', filename='imgs/apk.png') }}" class="float-left">
            {{ file_area(file) }}
        </div>
    {% endif %}
{% endmacro %}

{% macro index_group(group) %}
    <tr>
        <td><a href="{{ url_for('main.show_group', group_id=group.id) }}">
            <strong>{{ group.name }}</strong></a> <br>
            {{ group.intro|striptags|truncate(100,ture,'......') }}
        </td>
        <td>{{ group.get_topic_count() }}</td>
        <td>{{ group.get_post_count() }}</td>
        <td>{% if not group.get_last_topic() %}
            <div class="text-muted">还没发布主题</div>
            {% elif not group.get_last_post() or group.last_topic_sign()>=group.last_post_sign() %}
                <a href="{{ url_for('main.show_topic', topic_id=group.get_last_topic().id) }}">
                    {{ group.get_last_topic().name }}
                </a><br>
                <span class="text-muted"> 由
                    <a href="{{ url_for('user.index', username=group.get_last_topic().author.username) }}"
                       class="profile-popover" data-href="{{ url_for('ajax.get_profile',
                       user_id=group.get_last_topic().author_id) }}">
                        {{group.get_last_topic().author.username }}
                    </a> 发布<br>
                {{ moment(group.get_last_topic().timestamp).format('llll') }}</span>
            {% else %}
                <a href="{{ url_for('main.show_topic', topic_id=group.get_last_post().topic_id)}}">
                   {{ group.get_last_post().title }}</a> <br>
                <span class="text-muted"> 由
                    <a href="{{ url_for('user.index', username=group.get_last_post().author.username) }}"
                       class="profile-popover" data-href="{{ url_for('ajax.get_profile',
                       user_id=group.get_last_post().author.id) }}">
                        {{group.get_last_post().author.username }}
                    </a> 发布<br>
                {{ moment(group.get_last_post().timestamp).format('llll') }}</span>
            {% endif %}
        </td>
    </tr>
{% endmacro %}

{% macro photo_card(photo) %}
    <div class="card photo_card">
        <a href="{{ url_for('main.get_file', filename=photo.filename) }}" target="_blank">
            <img src="{{ url_for('main.get_file', filename=photo.filename_s)}}"></a>
        <div class="card-text small">
            <a href="{{ url_for('main.get_file', filename=photo.filename) }}" target="_blank">查看原图</a>&nbsp;&nbsp;
            {% if current_user==photo.post.author or current_user.can('MODERATE') or current_user==photo.topic.author %}
                <a data-toggle="modal" data-target="#confirm-delete" href="#!"
                    data-href="{{ url_for('main.delete_file', file_id=photo.id, next=request.full_path) }}" class="text-danger">删除</a>
            {% endif %}
        </div>
    </div>
{% endmacro %}